MyTaskProject/Models/ErrorViewModel.cs
using System;

namespace MyTaskProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyTaskProject/Models/TaskView.cs
using BusinessLogicLayer.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyTaskProject.Models
{
    public class TaskView
    {
        public string NameTask { get; set; }
        public string Description { get; set; }
        
        public string ApplicationUserId { get; set; }
    }
}

MyTaskProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.DTO;
using BusinessLogicLayer.Interface;
using AutoMapper;
using BusinessLogicLayer.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using MyTaskProject.Models;
using Microsoft.AspNetCore.Authorization;
using BusinessLogicLayer.Model;
using System.Security.Claims;
using MyTaskProject.Scripts;


namespace MyTaskProject.Controllers
{

    public class HomeController : Controller
    {
        ITaskService taskService;
        IWorkLogService workLogService;
        IMapper _mapper;
        public HomeController(ITaskService serv, IWorkLogService work, IMapper mapper)
        {
            taskService = serv;
            workLogService = work;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
        [HttpPost]
        public IActionResult CreateWorkLog([FromBody]IntermediateWorkLog workLog)
        {
            TimeConverter minute = new TimeConverter();
            workLog.Time = Convert.ToString(minute.ConvertingTime(workLog.Time));
            workLog.ApplicationUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var WokrLogDTO = _mapper.Map<IntermediateWorkLog, WorkLogDTO>(workLog);
            workLogService.CreateWorkLog(WokrLogDTO);
            return Redirect("~/Home/DashBoard");
        }

        [Authorize]
        public IActionResult DashBoard()
        {

            return View();
        }
        [HttpGet]
        public IActionResult AllTaskView()
        {
            IEnumerable<TaskDTO> taskDTOs = taskService.GetTasks();
            return Json(taskDTOs);
        }
        [HttpPost]
        public IActionResult WorkLogList([FromBody]SelectedDate date)
        {
            IEnumerable<TaskWorkLog> workLogDTOs = workLogService.GetWorkLogList(date.Date);
            return PartialView(workLogDTOs);
        }
        
    }
}

MyTaskProject/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using BusinessLogicLayer.DTO;
using BusinessLogicLayer.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using MyTaskProject.Models;

namespace MyTaskProject.Controllers
{
    public class TaskController : Controller
    {
        ITaskService taskService;
        IMapper _mapper;
        public TaskController(ITaskService serv, IMapper mapper)
        {
            _mapper = mapper;
            taskService = serv;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateTask(TaskViewModel task)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            task.ApplicationUserId = userId;
            var taskDTO = _mapper.Map<TaskViewModel, TaskDTO>(task);
            taskService.CreateTask(taskDTO);

            return Redirect("~/Home/Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            taskService.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyTaskProject/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MyTaskProject/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyTaskProject/Views/Home/DashBoard.cshtml
<div class="task-table" id="tasktable">
    <h2>
        {{topMessage}}
    </h2>

    <table class="table table-bordered table-primary task" data-url-get="@Url.Action("AllTaskView","Home")">
        <thead class="text-center">
            <tr >
                <th v-for="todo in todos">
                   {{ todo.day }}
                </th>
            </tr>
        </thead>
        @for (int i = 0; i < 5; i++)
        {
            <tr>
                @for (int j = 0; j < 7; j++)
                {
                    <td v-on:click="showAllWorkLogsOnThisDay($event)"></td>
                }
            </tr>
        }
    </table>
    <div class="btn-group form-group" role="group">
        <button type="button" class="btn btn-info" v-on:click="previousMonth">Previous Month</button>
        <button type="button" class="btn btn-info" v-on:click="nextMonth">Next Month</button>
    </div>
</div>


<div class="form-popup" id="formworklog">
    <form class="form-container" data-url-save="@Url.Action("CreateWorkLog","Home")">
        <h2>WorkLog</h2>
        <div class="form-group">
            Select Task:
            <select id="dropdown" class="form-control"></select>
        </div>
        <div class="form-group">
            Enter u time:
            <input type="text" class="form-control date" id="date" placeholder="Enter time like that 3w 2d 4h 5m"/>
            <span class="form-error">Please write u time like that 3w 2d 4h 5m </span>
        </div>
        <div class="form-group">
            Description:
            <input type="text" class="form-control" id="description" />
        </div>
        <div class="btn-group form-group" role="group">
            <button type="button" class="btn btn-success" id="worklog">Create</button>
            <button type="button" class="btn btn-danger" onclick="closeFormCreateWorkLog()">Close</button>
        </div>
    </form>
</div>



<div class="form-worklog-list" id="formworkloglist" data-url-dash="@Url.Action("WorkLogList","Home")">
    
</div>

MyTaskProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MyTaskProject/Views/Home/WorkLogList.cshtml
@using BusinessLogicLayer.Model
@model IEnumerable<TaskWorkLog>

<form class="form-container">
    <div class="btn-group form-group" role="group">
        <button type="button" class="btn btn-success" id="addWorkLog">Add</button>
        <button type="button" class="btn btn-danger" onclick="closeViewWorkLogList()">Close</button>
    </div>
    <div>
        @if (Model.Count() == 0||Model == null)
        {
            <h3>WorkLog is epmty</h3>
        }
        @foreach (var item in Model)
        {
            <div class="form-output">
                User name: @item.UserName
                <div class="form-output-lower">
                    <div>
                        Task name: @item.TaskName
                    </div>
                    Time: @Math.Round(item.Time / 60, 2) hour
                </div>
            </div>
        }
    </div>
</form>

MyTaskProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyTaskProject</title>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@7/dist/polyfill.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/window.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="DashBoard">DashBoard</a></li>
                    <li><a asp-area="" asp-controller="Task" asp-action="Index">Task</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MyTaskProject</p>
        </footer>
    </div>
    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/window.js"></script>
        <script src="~/js/tasktable.js"></script>
        <script src="~/js/site.js"asp-append-version="true" ></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">

        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

MyTaskProject/Views/Task/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using DataAccessLayer.Entities
@model MyTaskProject.Models.TaskView

<h1>@User.Identity.Name Hello</h1>
@using (Html.BeginForm("CreateTask", "Task", FormMethod.Post))

{

    <div class="form-horizontal">
        <div class="form-group">
            @{
                
            }
            @Html.LabelFor(model => model.NameTask, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.NameTask, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Task" class="btn btn-default" />
            </div>
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to Main", "Index", "Home")
</div>